id = "lux"
name = "Lux"
version = "0.0.1"
schema_version = 1
authors = ["Jeremy Banka <hello@jeremybanka.com>"]
description = "My cool extension"
repository = "https://github.com/jeremybanka/my-zed-theme"
