id = "lux"
name = "Lux Eternal"
version = "1.0.0"
schema_version = 1
authors = ["Jeremy Banka <hello@jeremybanka.com>"]
description = "Simple themes that emphasize usability, clear color blocking, and depth."
repository = "https://github.com/jeremybanka/lux-zed-themes"
